// app/lib/labs.ts

export type LabType = "simulation" | "exploration" | "editor"

export interface Lab {
  id: string
  name: string
  subject: "physics" | "chemistry" | "biology" | "computerScience"
  type: LabType
  challengeParams: string[]
  challengeEnabled: boolean
  description: string
}

export const LABS: Lab[] = [

  // ─── PHYSICS ───────────────────────────────────────────
  {
    id: "physics/freefall",
    name: "Free Fall",
    subject: "physics",
    type: "simulation",
    challengeParams: ["time", "velocity", "height"],
    challengeEnabled: true,
    description: "Free fall motion under gravity",
  },
  {
    id: "physics/projectilemotion",
    name: "Projectile Motion",
    subject: "physics",
    type: "simulation",
    challengeParams: ["range", "maxHeight", "time"],
    challengeEnabled: true,
    description: "Projectile motion analysis",
  },
  {
    id: "physics/simplependulum",
    name: "Simple Pendulum",
    subject: "physics",
    type: "simulation",
    challengeParams: ["period", "frequency"],
    challengeEnabled: true,
    description: "Pendulum oscillation experiment",
  },
  {
    id: "physics/hookelaw",
    name: "Hooke's Law",
    subject: "physics",
    type: "simulation",
    challengeParams: ["extension", "force"],
    challengeEnabled: true,
    description: "Spring force and extension",
  },
  {
    id: "physics/ohmslaw",
    name: "Ohm's Law",
    subject: "physics",
    type: "simulation",
    challengeParams: ["current", "voltage", "resistance"],
    challengeEnabled: true,
    description: "Voltage, current, and resistance",
  },
  {
    id: "physics/energyconservation",
    name: "Energy Conservation",
    subject: "physics",
    type: "simulation",
    challengeParams: ["kineticEnergy", "potentialEnergy"],
    challengeEnabled: true,
    description: "Conservation of mechanical energy",
  },
  {
    id: "physics/rclab",
    name: "RC Circuit",
    subject: "physics",
    type: "simulation",
    challengeParams: ["timeConstant", "voltage"],
    challengeEnabled: true,
    description: "RC circuit charge and discharge",
  },
  {
    id: "physics/speedoflight",
    name: "Speed of Light",
    subject: "physics",
    type: "exploration",
    challengeParams: ["wavelength", "frequency"],
    challengeEnabled: true,
    description: "Speed of light experiments",
  },
  {
    id: "physics/uniformmotionlab",
    name: "Uniform Motion",
    subject: "physics",
    type: "simulation",
    challengeParams: ["distance", "time", "speed"],
    challengeEnabled: true,
    description: "Constant velocity motion",
  },
  {
    id: "physics/waveoptics",
    name: "Wave Optics",
    subject: "physics",
    type: "exploration",
    challengeParams: ["fringeWidth", "wavelength"],
    challengeEnabled: true,
    description: "Wave optics and diffraction",
  },
  {
    id: "physics/opticslens",
    name: "Optics Lens",
    subject: "physics",
    type: "simulation",
    challengeParams: ["focalLength", "objectDistance"],
    challengeEnabled: true,
    description: "Explore optical lens behavior and image formation",
  },


  // ─── CHEMISTRY ─────────────────────────────────────────
  {
    id: "chemistry/periodictable",
    name: "Periodic Table",
    subject: "chemistry",
    type: "exploration",
    challengeParams: ["elementsVisited", "groupExplored", "periodExplored"],
    challengeEnabled: true,
    description: "Interactive periodic table explorer",
  },
  {
    id: "chemistry/chemicalbonds",
    name: "Chemical Bonds",
    subject: "chemistry",
    type: "exploration",
    challengeParams: ["bondsExplored"],
    challengeEnabled: true,
    description: "Ionic, covalent, and metallic bonding",
  },
  {
    id: "chemistry/electronic-configuration",
    name: "Electronic Configuration",
    subject: "chemistry",
    type: "exploration",
    challengeParams: ["elementsVisualized"],
    challengeEnabled: true,
    description: "Atomic structure and electron configuration",
  },
  {
    id: "chemistry/reaction-simulation",
    name: "Reaction Simulator",
    subject: "chemistry",
    type: "simulation",
    challengeParams: ["reactionsRun", "temperature", "yield"],
    challengeEnabled: true,
    description: "Chemical reaction builder",
  },
  {
    id: "chemistry/water-quality",
    name: "Water Quality Lab",
    subject: "chemistry",
    type: "exploration",
    challengeParams: ["labExplored"],
    challengeEnabled: true,
    description: "Test water quality parameters",
  },

  // ─── BIOLOGY ───────────────────────────────────────────
  {
    id: "biology/blood",
    name: "Blood Transfusion",
    subject: "biology",
    type: "exploration",
    challengeParams: ["bloodGroupTested"],
    challengeEnabled: true,
    description: "Blood group and transfusion compatibility",
  },
  {
    id: "biology/brainNeuron",
    name: "Brain Neuron",
    subject: "biology",
    type: "exploration",
    challengeParams: ["neuronsExplored"],
    challengeEnabled: true,
    description: "3D Brain Neuron Simulation",
  },
  {
    id: "biology/cell/animal",
    name: "Animal Cell",
    subject: "biology",
    type: "exploration",
    challengeParams: ["organellesExplored"],
    challengeEnabled: true,
    description: "3D interactive animal cell",
  },
  {
    id: "biology/cell/plant",
    name: "Plant Cell",
    subject: "biology",
    type: "exploration",
    challengeParams: ["organellesExplored"],
    challengeEnabled: true,
    description: "3D interactive plant cell",
  },
  {
    id: "biology/human",
    name: "Human Anatomy",
    subject: "biology",
    type: "exploration",
    challengeParams: ["structuresExplored"],
    challengeEnabled: true,
    description: "Human anatomy explorer",
  },
  {
    id: "biology/photosynthesis",
    name: "Photosynthesis",
    subject: "biology",
    type: "simulation",
    challengeParams: ["maxRateAchieved", "limitingFactorsIdentified"],
    challengeEnabled: true,
    description: "Explore variables affecting photosynthesis",
  },

  // ─── COMPUTER SCIENCE ──────────────────────────────────
  {
    id: "computer-science/code-lab/html-css-js",
    name: "HTML/CSS/JS Editor",
    subject: "computerScience",
    type: "editor",
    challengeParams: ["codeRuns", "consoleOutputMatched"],
    challengeEnabled: true,
    description: "Live web code editor",
  },
  {
    id: "computer-science/code-lab/js",
    name: "JS Event Loop Visualizer",
    subject: "computerScience",
    type: "editor",
    challengeParams: ["predictCorrect", "examplesCompleted", "freeformRunsCompleted"],
    challengeEnabled: true,
    description: "Interactive JavaScript event loop visualizer",
  },
  {
    id: "computer-science/dsa/sorting/bubble-sort",
    name: "Bubble Sort Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["arraysSorted", "swapsMade", "comparisonsMade"],
    challengeEnabled: true,
    description: "Visualize Bubble Sort algorithm",
  },
  {
    id: "computer-science/dsa/sorting/merge-sort",
    name: "Merge Sort Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["arraysSorted", "splitsMade", "mergesMade"],
    challengeEnabled: true,
    description: "Visualize Merge Sort algorithm",
  },
  {
    id: "computer-science/dsa/sorting/quick-sort",
    name: "Quick Sort Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["arraysSorted", "swapsMade", "comparisonsMade", "partitionsMade"],
    challengeEnabled: true,
    description: "Visualize Quick Sort algorithm",
  },
  {
    id: "computer-science/dsa/sorting/selection-sort",
    name: "Selection Sort Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["arraysSorted", "swapsMade", "comparisonsMade"],
    challengeEnabled: true,
    description: "Visualize Selection Sort algorithm",
  },
  {
    id: "computer-science/dsa/sorting/insertion-sort",
    name: "Insertion Sort Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["arraysSorted", "shiftsMade", "comparisonsMade"],
    challengeEnabled: true,
    description: "Visualize Insertion Sort algorithm",
  },
  {
    id: "computer-science/dsa/sorting/heap-sort",
    name: "Heap Sort Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["arraysSorted", "swapsMade", "comparisonsMade"],
    challengeEnabled: true,
    description: "Visualize Heap Sort algorithm",
  },
  {
    id: "computer-science/dsa/linked-list",
    name: "Linked List Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["algorithmsRun", "structuresExplored", "nodesAdded", "nodesDeleted"],
    challengeEnabled: true,
    description: "Visualize Linked List operations",
  },
  {
    id: "computer-science/dsa/queue",
    name: "Queue Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["algorithmsRun", "structuresExplored", "enqueues", "dequeues"],
    challengeEnabled: true,
    description: "Visualize Queue operations",
  },
  {
    id: "computer-science/dsa/stack",
    name: "Stack Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["algorithmsRun", "structuresExplored", "pushes", "pops"],
    challengeEnabled: true,
    description: "Visualize Stack operations",
  },
  {
    id: "computer-science/logic-gates/and-gate",
    name: "AND Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive AND Logic Gate",
  },
  {
    id: "computer-science/logic-gates/or-gate",
    name: "OR Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive OR Logic Gate",
  },
  {
    id: "computer-science/logic-gates/not-gate",
    name: "NOT Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive NOT Logic Gate",
  },
  {
    id: "computer-science/logic-gates/nand-gate",
    name: "NAND Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive NAND Logic Gate",
  },
  {
    id: "computer-science/logic-gates/nor-gate",
    name: "NOR Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive NOR Logic Gate",
  },
  {
    id: "computer-science/logic-gates/xor-gate",
    name: "XOR Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive XOR Logic Gate",
  },
  {
    id: "computer-science/logic-gates/xnor-gate",
    name: "XNOR Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive XNOR Logic Gate",
  },
  {
    id: "computer-science/ai-problem/hangman",
    name: "AI Hangman Solver",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["gamesPlayed", "wordsGuessed"],
    challengeEnabled: true,
    description: "AI Agent solving Hangman",
  },
  {
    id: "computer-science/ai-problem/hill-climb",
    name: "Hill Climbing Algorithm",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["stepsTaken", "restarts", "globalMaxFound"],
    challengeEnabled: true,
    description: "Visualize Hill Climbing AI Algorithm",
  },
  {
    id: "computer-science/ai-problem/maze-qlearn",
    name: "Q-Learning Maze",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["episodesRun", "successRate"],
    challengeEnabled: true,
    description: "RL Agent solving a maze",
  },
  {
    id: "computer-science/blockchain",
    name: "Blockchain Explorer",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["blocksCreated", "transactionsCreated"],
    challengeEnabled: true,
    description: "Blockchain technology explorer",
  },
  {
    id: "computer-science/git-simulator",
    name: "Git Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["commandsRun", "branchesCreated"],
    challengeEnabled: true,
    description: "Interactive Git version control",
  },
  {
    id: "computer-science/networking/osi-model",
    name: "OSI Model Lab",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["protocolsExplored", "layersExplored"],
    challengeEnabled: true,
    description: "Explore the 7 layers of OSI model",
  },
  {
    id: "computer-science/networking/packet-switching",
    name: "Packet Switching Lab",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["packetsRouted", "routersTraversed"],
    challengeEnabled: true,
    description: "Simulate packet switching in networks",
  },
  {
    id: "computer-science/networking/circuit-switching",
    name: "Circuit Switching Lab",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["circuitsEstablished", "callsCompleted"],
    challengeEnabled: true,
    description: "Simulate circuit switching networks",
  },
  {
    id: "computer-science/networking/topology-builder",
    name: "Network Topology Builder",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["nodesAdded", "linksAdded", "pingSuccess"],
    challengeEnabled: true,
    description: "Build and test network topologies",
  },
  {
    id: "computer-science/data-analyzer",
    name: "Data Analyzer",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["datasetsAnalyzed", "chartsGenerated"],
    challengeEnabled: true,
    description: "Data visualization and analysis",
  },
  {
    id: "computer-science/data-science",
    name: "Data Science",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["experimentsRun"],
    challengeEnabled: true,
    description: "Data science and ML experiments",
  },
]

export const getLabById = (id: string) => LABS.find(l => l.id === id)
export const getLabsBySubject = (subject: string) => LABS.filter(l => l.subject === subject)
export const getLabsByType = (type: LabType) => LABS.filter(l => l.type === type)