// app/lib/labs.ts

export type LabType = "simulation" | "exploration" | "editor"

export interface Lab {
  id: string
  name: string
  subject: "physics" | "chemistry" | "biology" | "computerScience" | "mathematics"
  type: LabType
  challengeParams: string[]
  challengeEnabled: boolean
  description: string
}

export const LABS: Lab[] = [

  // ─── PHYSICS ───────────────────────────────────────────
  {
    id: "physics/freefall",
    name: "Free Fall",
    subject: "physics",
    type: "simulation",
    challengeParams: ["time", "velocity", "height"],
    challengeEnabled: true,
    description: "Free fall motion under gravity",
  },
  {
    id: "physics/projectilemotion",
    name: "Projectile Motion",
    subject: "physics",
    type: "simulation",
    challengeParams: ["range", "maxHeight", "time"],
    challengeEnabled: true,
    description: "Projectile motion analysis",
  },
  {
    id: "physics/simplependulum",
    name: "Simple Pendulum",
    subject: "physics",
    type: "simulation",
    challengeParams: ["period", "frequency"],
    challengeEnabled: true,
    description: "Pendulum oscillation experiment",
  },
  {
    id: "physics/hookelaw",
    name: "Hooke's Law",
    subject: "physics",
    type: "simulation",
    challengeParams: ["extension", "force"],
    challengeEnabled: true,
    description: "Spring force and extension",
  },
  {
    id: "physics/ohmslaw",
    name: "Ohm's Law",
    subject: "physics",
    type: "simulation",
    challengeParams: ["current", "voltage", "resistance"],
    challengeEnabled: true,
    description: "Voltage, current, and resistance",
  },
  {
    id: "physics/energyconservation",
    name: "Energy Conservation",
    subject: "physics",
    type: "simulation",
    challengeParams: ["kineticEnergy", "potentialEnergy"],
    challengeEnabled: true,
    description: "Conservation of mechanical energy",
  },
  {
    id: "physics/rclab",
    name: "RC Circuit",
    subject: "physics",
    type: "simulation",
    challengeParams: ["timeConstant", "voltage"],
    challengeEnabled: true,
    description: "RC circuit charge and discharge",
  },
  {
    id: "physics/speedoflight",
    name: "Speed of Light",
    subject: "physics",
    type: "exploration",
    challengeParams: ["wavelength", "frequency"],
    challengeEnabled: true,
    description: "Speed of light experiments",
  },
  {
    id: "physics/uniformmotionlab",
    name: "Uniform Motion",
    subject: "physics",
    type: "simulation",
    challengeParams: ["distance", "time", "speed"],
    challengeEnabled: true,
    description: "Constant velocity motion",
  },
  {
    id: "physics/waveoptics",
    name: "Wave Optics",
    subject: "physics",
    type: "exploration",
    challengeParams: ["fringeWidth", "wavelength"],
    challengeEnabled: true,
    description: "Wave optics and diffraction",
  },
  {
    id: "physics/opticslens",
    name: "Optics Lens",
    subject: "physics",
    type: "simulation",
    challengeParams: ["focalLength", "objectDistance"],
    challengeEnabled: true,
    description: "Explore optical lens behavior and image formation",
  },
  {
    id: "physics/faradays-law",
    name: "Electromagnetic Induction & Faraday's Law",
    subject: "physics",
    type: "simulation",
    challengeParams: ["fluxChanged", "emfGenerated", "turnsExplored"],
    challengeEnabled: true,
    description: "Draggable bar magnet, vector field lines, multi-turn coils, and live galvanometer deflection",
  },
  {
    id: "physics/photoelectric-effect",
    name: "Photoelectric Effect & Quantum Photons",
    subject: "physics",
    type: "simulation",
    challengeParams: ["photonsFired", "electronsEjected", "stoppingVoltageMeasured"],
    challengeEnabled: true,
    description: "Monochromatic photon frequency sweep, work functions, photoelectron ejection, and stopping potential",
  },
  {
    id: "physics/thermodynamics",
    name: "Thermodynamic Heat Engines & Carnot Cycle",
    subject: "physics",
    type: "simulation",
    challengeParams: ["cyclesCompleted", "efficiencyMeasured", "workOutput"],
    challengeEnabled: true,
    description: "4-stroke Carnot cycle, isothermal/adiabatic expansion & compression, and live P-V indicator loops",
  },



  // ─── CHEMISTRY ─────────────────────────────────────────
  {
    id: "chemistry/periodictable",
    name: "Periodic Table",
    subject: "chemistry",
    type: "exploration",
    challengeParams: ["elementsVisited", "groupExplored", "periodExplored"],
    challengeEnabled: true,
    description: "Interactive periodic table explorer",
  },
  {
    id: "chemistry/chemicalbonds",
    name: "Chemical Bonds",
    subject: "chemistry",
    type: "exploration",
    challengeParams: ["bondsExplored"],
    challengeEnabled: true,
    description: "Ionic, covalent, and metallic bonding",
  },
  {
    id: "chemistry/electronic-configuration",
    name: "Electronic Configuration",
    subject: "chemistry",
    type: "exploration",
    challengeParams: ["elementsVisualized"],
    challengeEnabled: true,
    description: "Atomic structure and electron configuration",
  },
  {
    id: "chemistry/reaction-simulation",
    name: "Reaction Simulator",
    subject: "chemistry",
    type: "simulation",
    challengeParams: ["reactionsRun", "temperature", "yield"],
    challengeEnabled: true,
    description: "Chemical reaction builder",
  },
  {
    id: "chemistry/water-quality",
    name: "Water Quality Lab",
    subject: "chemistry",
    type: "exploration",
    challengeParams: ["labExplored"],
    challengeEnabled: true,
    description: "Test water quality parameters",
  },
  {
    id: "chemistry/titration",
    name: "Virtual Titration",
    subject: "chemistry",
    type: "simulation",
    challengeParams: ["volumeUsed", "calculatedConcentration"],
    challengeEnabled: true,
    description: "Virtual acid-base titration lab",
  },
  {
    id: "chemistry/flame-test",
    name: "Flame Test & Atomic Emission Spectrometry",
    subject: "chemistry",
    type: "simulation",
    challengeParams: ["saltsTested", "photonsEmitted", "spectraAnalyzed"],
    challengeEnabled: true,
    description: "Bunsen air collar combustion, metal cation electron excitation, photon emission, and discrete spectroscope lines",
  },
  {
    id: "chemistry/vsepr-geometry",
    name: "3D Molecular Geometry & VSEPR Studio",
    subject: "chemistry",
    type: "simulation",
    challengeParams: ["geometriesBuilt", "anglesMeasured", "dipolesCalculated"],
    challengeEnabled: true,
    description: "Rotatable 3D electrostatic domain repulsions, orbital hybridization, bond angles, and net dipole vectors",
  },
  {
    id: "chemistry/electrochemistry",
    name: "Electrochemical Galvanic & Electrolytic Cells",
    subject: "chemistry",
    type: "simulation",
    challengeParams: ["cellsBuilt", "voltageMeasured", "massTransferred"],
    challengeEnabled: true,
    description: "Galvanic & electrolytic redox reactions, electron wire flow, salt bridge migration, and Nernst equation",
  },
  {
    id: "chemistry/gas-laws",
    name: "Gas Laws & Maxwell-Boltzmann Kinetic Theory",
    subject: "chemistry",
    type: "simulation",
    challengeParams: ["compressionsRun", "temperatureScaled", "distributionsTraced"],
    challengeEnabled: true,
    description: "2D elastic particle collisions, draggable piston volume, thermal bath velocity, and live Maxwell-Boltzmann curves",
  },


  // ─── BIOLOGY ───────────────────────────────────────────
  {
    id: "biology/blood",
    name: "Blood Transfusion",
    subject: "biology",
    type: "exploration",
    challengeParams: ["bloodGroupTested"],
    challengeEnabled: true,
    description: "Blood group and transfusion compatibility",
  },
  {
    id: "biology/brainNeuron",
    name: "Brain Neuron",
    subject: "biology",
    type: "exploration",
    challengeParams: ["neuronsExplored"],
    challengeEnabled: true,
    description: "3D Brain Neuron Simulation",
  },
  {
    id: "biology/cell/animal",
    name: "Animal Cell",
    subject: "biology",
    type: "exploration",
    challengeParams: ["organellesExplored"],
    challengeEnabled: true,
    description: "3D interactive animal cell",
  },
  {
    id: "biology/cell/plant",
    name: "Plant Cell",
    subject: "biology",
    type: "exploration",
    challengeParams: ["organellesExplored"],
    challengeEnabled: true,
    description: "3D interactive plant cell",
  },
  {
    id: "biology/human",
    name: "Human Anatomy",
    subject: "biology",
    type: "exploration",
    challengeParams: ["structuresExplored"],
    challengeEnabled: true,
    description: "Human anatomy explorer",
  },
  {
    id: "biology/photosynthesis",
    name: "Photosynthesis",
    subject: "biology",
    type: "simulation",
    challengeParams: ["maxRateAchieved", "limitingFactorsIdentified"],
    challengeEnabled: true,
    description: "Explore variables affecting photosynthesis",
  },
  {
    id: "biology/genetics/monohybrid",
    name: "Monohybrid Punnett Square",
    subject: "biology",
    type: "simulation",
    challengeParams: ["crossesCompleted", "batchBreedsRun"],
    challengeEnabled: true,
    description: "Single-trait inheritance with creature avatars and 100-offspring breeder",
  },
  {
    id: "biology/genetics/dihybrid",
    name: "Dihybrid Cross & Assortment",
    subject: "biology",
    type: "simulation",
    challengeParams: ["crossesCompleted"],
    challengeEnabled: true,
    description: "16-cell dihybrid cross tracking 2 traits with 9:3:3:1 ratios",
  },
  {
    id: "biology/genetics/transcription-translation",
    name: "DNA Transcription & Translation",
    subject: "biology",
    type: "simulation",
    challengeParams: ["proteinsSynthesized", "mutationsTested"],
    challengeEnabled: true,
    description: "Central Dogma mRNA synthesis and ribosomal tRNA codon translation",
  },
  {
    id: "biology/genetics/pedigree",
    name: "Pedigree Tree & Inheritance",
    subject: "biology",
    type: "exploration",
    challengeParams: ["membersInspected", "modesExplored"],
    challengeEnabled: true,
    description: "3-generation family tree analyzer for Autosomal and X-Linked traits",
  },
  {
    id: "biology/enzyme-kinetics",
    name: "Enzyme Kinetics & Catalysis Studio",
    subject: "biology",
    type: "simulation",
    challengeParams: ["reactionsCatalyzed", "vmaxCalculated", "inhibitorsTested"],
    challengeEnabled: true,
    description: "Active site induced fit, competitive/non-competitive inhibition, and live Michaelis-Menten & Lineweaver-Burk plots",
  },
  {
    id: "biology/cellular-respiration",
    name: "Cellular Respiration & Mitochondrial Electron Transport",
    subject: "biology",
    type: "simulation",
    challengeParams: ["glucoseProcessed", "atpSynthesized", "gradientPumped"],
    challengeEnabled: true,
    description: "Glycolysis, Krebs cycle, inner mitochondrial membrane proton gradient pumping, and rotary ATP Synthase",
  },
  {
    id: "biology/osmosis-tonicity",
    name: "Osmosis, Diffusion & Cell Tonicity",
    subject: "biology",
    type: "simulation",
    challengeParams: ["solutesEquilibrated", "rbcLysisTested", "turgorMeasured"],
    challengeEnabled: true,
    description: "Semi-permeable membrane pore filtering, osmotic pressure gradients, RBC hemolysis/crenation, and plant turgor",
  },


  // ─── COMPUTER SCIENCE ──────────────────────────────────
  {
    id: "computer-science/code-lab/html-css-js",
    name: "HTML/CSS/JS Editor",
    subject: "computerScience",
    type: "editor",
    challengeParams: ["codeRuns", "consoleOutputMatched"],
    challengeEnabled: true,
    description: "Live web code editor",
  },
  {
    id: "computer-science/code-lab/js",
    name: "JS Event Loop Visualizer",
    subject: "computerScience",
    type: "editor",
    challengeParams: ["predictCorrect", "examplesCompleted", "freeformRunsCompleted"],
    challengeEnabled: true,
    description: "Interactive JavaScript event loop visualizer",
  },
  {
    id: "computer-science/cpu-architecture",
    name: "CPU Micro-Architecture & 8-Bit Assembly",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["programsExecuted", "cyclesStepped", "registersModified"],
    challengeEnabled: true,
    description: "8-bit assembly editor, 4-stage instruction cycle, datapath bus animation, and register file",
  },
  {
    id: "computer-science/bitwise-operations",
    name: "Binary & Bitwise Operations Studio",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["bitsToggled", "operationsCalculated", "masksApplied"],
    challengeEnabled: true,
    description: "Interactive 8-bit register tiles, bitwise logic gates, shifts, rotations, Two's complement, and mask hacks",
  },

  {
    id: "computer-science/dsa/sorting/bubble-sort",
    name: "Bubble Sort Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["arraysSorted", "swapsMade", "comparisonsMade"],
    challengeEnabled: true,
    description: "Visualize Bubble Sort algorithm",
  },
  {
    id: "computer-science/dsa/sorting/merge-sort",
    name: "Merge Sort Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["arraysSorted", "splitsMade", "mergesMade"],
    challengeEnabled: true,
    description: "Visualize Merge Sort algorithm",
  },
  {
    id: "computer-science/dsa/sorting/quick-sort",
    name: "Quick Sort Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["arraysSorted", "swapsMade", "comparisonsMade", "partitionsMade"],
    challengeEnabled: true,
    description: "Visualize Quick Sort algorithm",
  },
  {
    id: "computer-science/dsa/sorting/selection-sort",
    name: "Selection Sort Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["arraysSorted", "swapsMade", "comparisonsMade"],
    challengeEnabled: true,
    description: "Visualize Selection Sort algorithm",
  },
  {
    id: "computer-science/dsa/sorting/insertion-sort",
    name: "Insertion Sort Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["arraysSorted", "shiftsMade", "comparisonsMade"],
    challengeEnabled: true,
    description: "Visualize Insertion Sort algorithm",
  },
  {
    id: "computer-science/dsa/sorting/heap-sort",
    name: "Heap Sort Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["arraysSorted", "swapsMade", "comparisonsMade"],
    challengeEnabled: true,
    description: "Visualize Heap Sort algorithm",
  },
  {
    id: "computer-science/dsa/linked-list",
    name: "Linked List Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["algorithmsRun", "structuresExplored", "nodesAdded", "nodesDeleted"],
    challengeEnabled: true,
    description: "Visualize Linked List operations",
  },
  {
    id: "computer-science/dsa/queue",
    name: "Queue Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["algorithmsRun", "structuresExplored", "enqueues", "dequeues"],
    challengeEnabled: true,
    description: "Visualize Queue operations",
  },
  {
    id: "computer-science/dsa/stack",
    name: "Stack Visualizer",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["algorithmsRun", "structuresExplored", "pushes", "pops"],
    challengeEnabled: true,
    description: "Visualize Stack operations",
  },
  {
    id: "computer-science/logic-gates/and-gate",
    name: "AND Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive AND Logic Gate",
  },
  {
    id: "computer-science/logic-gates/or-gate",
    name: "OR Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive OR Logic Gate",
  },
  {
    id: "computer-science/logic-gates/not-gate",
    name: "NOT Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive NOT Logic Gate",
  },
  {
    id: "computer-science/logic-gates/nand-gate",
    name: "NAND Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive NAND Logic Gate",
  },
  {
    id: "computer-science/logic-gates/nor-gate",
    name: "NOR Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive NOR Logic Gate",
  },
  {
    id: "computer-science/logic-gates/xor-gate",
    name: "XOR Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive XOR Logic Gate",
  },
  {
    id: "computer-science/logic-gates/xnor-gate",
    name: "XNOR Gate Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["inputsToggled", "trueOutputsAchieved"],
    challengeEnabled: true,
    description: "Interactive XNOR Logic Gate",
  },
  {
    id: "computer-science/ai-problem/hangman",
    name: "AI Hangman Solver",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["gamesPlayed", "wordsGuessed"],
    challengeEnabled: true,
    description: "AI Agent solving Hangman",
  },
  {
    id: "computer-science/ai-problem/hill-climb",
    name: "Hill Climbing Algorithm",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["stepsTaken", "restarts", "globalMaxFound"],
    challengeEnabled: true,
    description: "Visualize Hill Climbing AI Algorithm",
  },
  {
    id: "computer-science/ai-problem/maze-qlearn",
    name: "Q-Learning Maze",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["episodesRun", "successRate"],
    challengeEnabled: true,
    description: "RL Agent solving a maze",
  },
  {
    id: "computer-science/blockchain",
    name: "Blockchain Explorer",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["blocksCreated", "transactionsCreated"],
    challengeEnabled: true,
    description: "Blockchain technology explorer",
  },
  {
    id: "computer-science/git-simulator",
    name: "Git Simulator",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["commandsRun", "branchesCreated"],
    challengeEnabled: true,
    description: "Interactive Git version control",
  },
  {
    id: "computer-science/networking/osi-model",
    name: "OSI Model Lab",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["protocolsExplored", "layersExplored"],
    challengeEnabled: true,
    description: "Explore the 7 layers of OSI model",
  },
  {
    id: "computer-science/networking/packet-switching",
    name: "Packet Switching Lab",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["packetsRouted", "routersTraversed"],
    challengeEnabled: true,
    description: "Simulate packet switching in networks",
  },
  {
    id: "computer-science/dsa/graph-algorithms",
    name: "Graph Algorithms & Network Flow",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["pathsFound", "mstsComputed", "graphsColored"],
    challengeEnabled: true,
    description: "Interactive Dijkstra shortest path, Kruskal and Prim MST, chromatic vertex coloring, and Ford-Fulkerson max flow",
  },
  {
    id: "computer-science/networking/circuit-switching",
    name: "Circuit Switching Lab",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["circuitsEstablished", "callsCompleted"],
    challengeEnabled: true,
    description: "Simulate circuit switching networks",
  },
  {
    id: "computer-science/networking/topology-builder",
    name: "Network Topology Builder",
    subject: "computerScience",
    type: "simulation",
    challengeParams: ["nodesAdded", "linksAdded", "pingSuccess"],
    challengeEnabled: true,
    description: "Build and test network topologies",
  },
  {
    id: "computer-science/data-analyzer",
    name: "Data Analyzer",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["datasetsAnalyzed", "chartsGenerated"],
    challengeEnabled: true,
    description: "Data visualization and analysis",
  },
  {
    id: "computer-science/data-science",
    name: "Data Science",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["experimentsRun"],
    challengeEnabled: true,
    description: "Data science and ML experiments",
  },
  {
    id: "computer-science/cryptography",
    name: "Classical & Modern Cryptography",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["ciphersEncrypted", "keysAgreed", "hashesMined"],
    challengeEnabled: true,
    description: "Interactive Caesar cipher wheel, Vigenère table, WWII Enigma machine, Diffie-Hellman keys, and SHA-256 mining",
  },
  {
    id: "computer-science/cryptography/caesar",
    name: "Caesar Cipher Studio",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["ciphersEncrypted"],
    challengeEnabled: true,
    description: "Interactive rotating Caesar cipher wheel and frequency cracker",
  },
  {
    id: "computer-science/cryptography/vigenere",
    name: "Vigenère Cipher Studio",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["ciphersEncrypted"],
    challengeEnabled: true,
    description: "Polyalphabetic Vigenère 26x26 Tabula Recta matrix lookup",
  },
  {
    id: "computer-science/cryptography/enigma",
    name: "WWII Enigma Machine Simulator",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["ciphersEncrypted"],
    challengeEnabled: true,
    description: "3-rotor Enigma machine with plugboard and glowing lampboards",
  },
  {
    id: "computer-science/cryptography/diffie-hellman",
    name: "Diffie-Hellman Key Exchange",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["keysAgreed"],
    challengeEnabled: true,
    description: "Asymmetric paint color-mixing and modular math key exchange",
  },
  {
    id: "computer-science/cryptography/sha256",
    name: "SHA-256 & Bitcoin Mining",
    subject: "computerScience",
    type: "exploration",
    challengeParams: ["hashesMined"],
    challengeEnabled: true,
    description: "256-bit Avalanche Effect and live Proof-of-Work Bitcoin mining",
  },

  // ─── MATHEMATICS ───────────────────────────────────────
  {
    id: "mathematics/functiongrapher",
    name: "Function Grapher",
    subject: "mathematics",
    type: "exploration",
    challengeParams: ["rootsFound", "functionsPlotted", "transformationsApplied"],
    challengeEnabled: true,
    description: "Interactive function plotter with real-time transformations and analysis",
  },
  {
    id: "mathematics/trigonometry",
    name: "Trigonometry Visualizer",
    subject: "mathematics",
    type: "exploration",
    challengeParams: ["anglesExplored", "identitiesVerified", "wavesTransformed"],
    challengeEnabled: true,
    description: "Interactive Unit Circle, right-triangle trigonometric ratios, and wave unfolding",
  },
  {
    id: "mathematics/polynomials",
    name: "Quadratic & Polynomial Explorer",
    subject: "mathematics",
    type: "exploration",
    challengeParams: ["rootsFound", "discriminantAnalyzed", "polynomialsSolved"],
    challengeEnabled: true,
    description: "Interactive parabola geometry, discriminant analysis (Δ = b² - 4ac), and synthetic division",
  },
  {
    id: "mathematics/calculus",
    name: "Calculus & Derivatives Sandbox",
    subject: "mathematics",
    type: "exploration",
    challengeParams: ["limitsApproached", "integralsComputed", "extremaFound"],
    challengeEnabled: true,
    description: "Interactive secant-to-tangent limits, difference quotients, Riemann sums, and optimization",
  },
  {
    id: "mathematics/linear-algebra",
    name: "Linear Algebra & Matrix Transformations",
    subject: "mathematics",
    type: "exploration",
    challengeParams: ["determinantsComputed", "eigenvectorsFound", "transformsApplied"],
    challengeEnabled: true,
    description: "Interactive 2D space transformation, basis vectors î & ĵ, determinant scaling, and eigenvalues",
  },
  {
    id: "mathematics/statistics",
    name: "Probability & Statistics Sandbox",
    subject: "mathematics",
    type: "exploration",
    challengeParams: ["samplesGenerated", "distributionsExplored", "regressionsFitted"],
    challengeEnabled: true,
    description: "Interactive Galton bean machine, Central Limit Theorem, probability distributions, and OLS regression",
  },
  {
    id: "mathematics/complex-numbers",
    name: "Complex Numbers & Fractals Explorer",
    subject: "mathematics",
    type: "exploration",
    challengeParams: ["complexOperationsPerformed", "rootsExplored", "fractalsRendered"],
    challengeEnabled: true,
    description: "Interactive Argand plane, rotation-dilation multiplication, roots of unity, Euler's identity, and Mandelbrot/Julia set zoomer",
  },
  {
    id: "mathematics/set-theory",
    name: "Set Theory & Boolean Algebra",
    subject: "mathematics",
    type: "exploration",
    challengeParams: ["regionsShaded", "operationsEvaluated", "functionsMapped"],
    challengeEnabled: true,
    description: "Interactive 2/3-set Venn diagrams, set operations evaluator, Inclusion-Exclusion, and function mappings",
  },
  {
    id: "mathematics/geometry",
    name: "Interactive Geometry Studio",
    subject: "mathematics",
    type: "exploration",
    challengeParams: ["constructionsMade", "centersExplored", "theoremsTested"],
    challengeEnabled: true,
    description: "Interactive geometric constructions, triangle centers & Euler line, circle theorems, and 2D transformations",
  },
  {
    id: "mathematics/vector-algebra",
    name: "Vector Algebra & 3D Space",
    subject: "mathematics",
    type: "exploration",
    challengeParams: ["operationsPerformed", "productsComputed", "projectionsTested"],
    challengeEnabled: true,
    description: "Interactive 2D vector operations, dot & cross products, projections, scalar triple product, and 3D space",
  },
  {
    id: "mathematics/combinatorics",
    name: "Combinatorics & Discrete Counting",
    subject: "mathematics",
    type: "exploration",
    challengeParams: ["countsComputed", "trianglesExplored", "partitionsGenerated"],
    challengeEnabled: true,
    description: "Permutations & combinations, Pascal's triangle patterns, binomial expansions, Pigeonhole principle, and stars & bars",
  },
  {
    id: "mathematics/number-theory",
    name: "Number Theory & Cryptography",
    subject: "mathematics",
    type: "exploration",
    challengeParams: ["primesFactored", "gcdsComputed", "ciphersTested"],
    challengeEnabled: true,
    description: "Primes & sieves, Euclidean GCD tiling, modular arithmetic & CRT, Euler's totient, RSA cryptography, and Collatz orbits",
  },
  {
    id: "mathematics/differential-equations",
    name: "Differential Equations & Dynamical Systems",
    subject: "mathematics",
    type: "simulation",
    challengeParams: ["equationsIntegrated", "phaseSystemsExplored", "chaosTrajectoriesTested"],
    challengeEnabled: true,
    description: "Slope fields & RK4 integrators, 2D phase planes, Lotka-Volterra predator-prey dynamics, 3D Lorenz chaos, and SIR epidemic curves",
  },
]

export const getLabById = (id: string) => LABS.find(l => l.id === id)
export const getLabsBySubject = (subject: string) => LABS.filter(l => l.subject === subject)
export const getLabsByType = (type: LabType) => LABS.filter(l => l.type === type)

export function resolveLabIdFromPath(pathname: string): string | null {
  if (!pathname) return null;
  const cleaned = pathname.replace(/^\/labs\//, "").replace(/^\//, "").replace(/\/$/, "");
  if (!cleaned) return null;
  
  // Exact match
  const exact = LABS.find((l) => l.id === cleaned);
  if (exact) return exact.id;

  // Prefix match for sub-routes (e.g. chemistry/periodictable/atom/46 -> chemistry/periodictable)
  const prefixMatch = LABS.find((l) => cleaned.startsWith(`${l.id}/`));
  if (prefixMatch) return prefixMatch.id;

  return null;
}