// app/lib/knowledge/concepts/biology.ts
import { ConceptEntity } from "../../types/knowledge";

export const BIOLOGY_CONCEPTS: ConceptEntity[] = [
  {
    id: "cell-animal",
    slug: "/biology/cell/animal",
    title: "3D Animal Cell Structure & Organelles",
    subject: "biology",
    domain: "Cytology",
    topic: "Cellular Biology",
    description: "Explore the nucleus, mitochondria, endoplasmic reticulum, Golgi apparatus, and plasma membrane.",
    quickAnswer: "An animal cell is a eukaryotic cell enclosed by a plasma membrane containing membrane-bound organelles such as the nucleus and mitochondria.",
    prerequisites: [],
    nextTopics: ["cell-plant", "human"],
    siblingTopics: ["cell-plant"],
    relatedLabs: ["biology/cell/animal"],
    relatedBlogs: [],
    difficulty: "beginner",
    educationalLevel: "middleSchool",
    tags: ["organelles", "mitochondria", "nucleus", "eukaryote"],
  },
  {
    id: "cell-plant",
    slug: "/biology/cell/plant",
    title: "3D Plant Cell Structure & Chloroplasts",
    subject: "biology",
    domain: "Cytology",
    topic: "Cellular Biology",
    description: "Investigate plant cell walls, central vacuoles, chloroplasts, and turgor pressure.",
    quickAnswer: "Plant cells feature rigid cell walls, large central vacuoles, and chloroplasts for photosynthesis.",
    prerequisites: ["cell-animal"],
    nextTopics: ["photosynthesis"],
    siblingTopics: ["cell-animal"],
    relatedLabs: ["biology/cell/plant"],
    relatedBlogs: [],
    difficulty: "beginner",
    educationalLevel: "middleSchool",
    tags: ["chloroplast", "cell wall", "vacuole", "turgor"],
  },
  {
    id: "photosynthesis",
    slug: "/biology/photosynthesis",
    title: "Photosynthesis & Light Reactions",
    subject: "biology",
    domain: "Plant Physiology",
    topic: "Bioenergetics",
    description: "Investigate light-dependent reactions, Calvin cycle, carbon fixation, and Blackman's limiting factors.",
    quickAnswer: "Photosynthesis is the biological process by which autotrophs convert light energy, carbon dioxide, and water into glucose and oxygen.",
    prerequisites: ["cell-plant"],
    nextTopics: [],
    siblingTopics: ["cell-plant"],
    relatedLabs: ["biology/photosynthesis"],
    relatedBlogs: [],
    formulas: ["photosynthesis-equation"],
    difficulty: "intermediate",
    educationalLevel: "highSchool",
    tags: ["chloroplast", "calvin cycle", "chlorophyll", "glucose"],
  },
  {
    id: "brainNeuron",
    slug: "/biology/brainNeuron",
    title: "Neuron Signal Transmission & Brain Structure",
    subject: "biology",
    domain: "Neurobiology",
    topic: "Nervous System",
    description: "Model action potentials, resting membrane potential, dendrites, axon hillock, and synaptic transmission.",
    quickAnswer: "Neurons transmit electrical action potentials down their axons and release chemical neurotransmitters across synapses.",
    prerequisites: [],
    nextTopics: ["human"],
    siblingTopics: ["human"],
    relatedLabs: ["biology/brainNeuron"],
    relatedBlogs: [],
    formulas: ["action-potential-nernst"],
    difficulty: "intermediate",
    educationalLevel: "undergraduate",
    tags: ["neuron", "action potential", "synapse", "neurobiology"],
  },
  {
    id: "blood",
    slug: "/biology/blood",
    title: "Blood Group Typing & Transfusion Compatibility",
    subject: "biology",
    domain: "Immunology",
    topic: "Hematology",
    description: "Explore ABO blood groups, Rh factor, agglutination reactions, and universal donors/recipients.",
    quickAnswer: "Blood groups are classified by RBC surface antigens (A, B, Rh) and plasma antibodies, determining transfusion compatibility.",
    prerequisites: [],
    nextTopics: ["human"],
    siblingTopics: ["human"],
    relatedLabs: ["biology/blood"],
    relatedBlogs: [],
    difficulty: "beginner",
    educationalLevel: "highSchool",
    tags: ["blood type", "abo", "antigen", "agglutination"],
  },
  {
    id: "human",
    slug: "/biology/human",
    title: "Human Anatomy Systems & Organ Dynamics",
    subject: "biology",
    domain: "Anatomy & Physiology",
    topic: "Organ Systems",
    description: "Explore skeletal, muscular, circulatory, respiratory, and digestive organ system interactions.",
    quickAnswer: "Human anatomy organizes cells, tissues, and organ systems to maintain body homeostasis.",
    prerequisites: ["cell-animal"],
    nextTopics: ["brainNeuron"],
    siblingTopics: ["blood"],
    relatedLabs: ["biology/human"],
    relatedBlogs: [],
    difficulty: "intermediate",
    educationalLevel: "highSchool",
    tags: ["anatomy", "organ systems", "circulatory", "respiratory"],
  },
];
