// app/lib/knowledge/concepts/chemistry.ts
import { ConceptEntity } from "../../types/knowledge";

export const CHEMISTRY_CONCEPTS: ConceptEntity[] = [
  {
    id: "titration",
    slug: "/chemistry/titration",
    title: "Acid-Base & Redox Titration",
    subject: "chemistry",
    domain: "Analytical Chemistry",
    topic: "Volumetric Analysis",
    description: "Determine unknown solution concentrations using equivalence endpoints, indicator color changes, and C1V1=C2V2 stoichiometry.",
    quickAnswer: "Titration is a quantitative chemical analysis where a solution of known concentration (titrant) is added to a solution of unknown concentration (analyte) until the equivalence point is reached.",
    prerequisites: ["chemicalbonds"],
    nextTopics: ["water-quality"],
    siblingTopics: ["reaction-simulation"],
    relatedLabs: ["chemistry/titration"],
    relatedBlogs: [],
    formulas: ["titration-stoichiometry", "ph-formula"],
    difficulty: "intermediate",
    educationalLevel: "highSchool",
    tags: ["titration", "ph", "acid base", "equivalence point", "stoichiometry"],
  },
  {
    id: "periodictable",
    slug: "/chemistry/periodictable",
    title: "Periodic Trends & Atomic Properties",
    subject: "chemistry",
    domain: "Inorganic Chemistry",
    topic: "Periodic Table",
    description: "Explore atomic radius, electronegativity, ionization energy, and periodic group trends.",
    quickAnswer: "The periodic table organizes elements by increasing atomic number, displaying recurring chemical properties across periods and groups.",
    prerequisites: ["electronic-configuration"],
    nextTopics: ["chemicalbonds"],
    siblingTopics: ["electronic-configuration"],
    relatedLabs: ["chemistry/periodictable"],
    relatedBlogs: [],
    difficulty: "beginner",
    educationalLevel: "middleSchool",
    tags: ["elements", "atomic number", "electronegativity", "periodic table"],
  },
  {
    id: "chemicalbonds",
    slug: "/chemistry/chemicalbonds",
    title: "Ionic, Covalent & Metallic Bonding",
    subject: "chemistry",
    domain: "Physical Chemistry",
    topic: "Chemical Bonding",
    description: "Understand electron transfer, electron sharing, lattice energy, and molecular geometry.",
    quickAnswer: "Chemical bonding describes the electrostatic attraction between atoms or ions, classified into ionic (transfer), covalent (sharing), and metallic (delocalized sea) bonds.",
    prerequisites: ["periodictable"],
    nextTopics: ["reaction-simulation", "titration"],
    siblingTopics: ["periodictable"],
    relatedLabs: ["chemistry/chemicalbonds"],
    relatedBlogs: [],
    difficulty: "intermediate",
    educationalLevel: "highSchool",
    tags: ["covalent", "ionic", "valence", "bonding"],
  },
  {
    id: "electronic-configuration",
    slug: "/chemistry/electronic-configuration",
    title: "Electronic Configuration & Orbital Filling",
    subject: "chemistry",
    domain: "Physical Chemistry",
    topic: "Quantum Structure",
    description: "Master Aufbau principle, Pauli exclusion, and Hund's rule for orbital electron configurations.",
    quickAnswer: "Electronic configuration describes the distribution of electrons in atomic orbitals following energy subshell order.",
    prerequisites: [],
    nextTopics: ["periodictable"],
    siblingTopics: ["periodictable"],
    relatedLabs: ["chemistry/electronic-configuration"],
    relatedBlogs: [],
    difficulty: "beginner",
    educationalLevel: "highSchool",
    tags: ["orbitals", "electron configuration", "aufbau", "subshells"],
  },
  {
    id: "reaction-simulation",
    slug: "/chemistry/reaction-simulation",
    title: "Chemical Reaction Kinematics & Yield",
    subject: "chemistry",
    domain: "Physical Chemistry",
    topic: "Reaction Kinetics",
    description: "Simulate reactant collisions, activation energy, catalysts, and percent yield.",
    quickAnswer: "Chemical reaction kinetics studies reaction rates, temperature dependence, and molecular collision dynamics.",
    prerequisites: ["chemicalbonds"],
    nextTopics: ["titration"],
    siblingTopics: ["titration"],
    relatedLabs: ["chemistry/reaction-simulation"],
    relatedBlogs: [],
    difficulty: "intermediate",
    educationalLevel: "highSchool",
    tags: ["kinetics", "reaction rate", "activation energy", "yield"],
  },
  {
    id: "water-quality",
    slug: "/chemistry/water-quality",
    title: "Water Quality Parameters & Hydrochemistry",
    subject: "chemistry",
    domain: "Environmental Chemistry",
    topic: "Water Testing",
    description: "Test pH, dissolved oxygen, turbidity, hardness, and contaminant thresholds.",
    quickAnswer: "Water quality assessment measures chemical, physical, and biological characteristics relative to safety standards.",
    prerequisites: ["titration"],
    nextTopics: [],
    siblingTopics: ["titration"],
    relatedLabs: ["chemistry/water-quality"],
    relatedBlogs: [],
    difficulty: "beginner",
    educationalLevel: "highSchool",
    tags: ["water quality", "ph", "dissolved oxygen", "turbidity"],
  },
];
