// app/lib/knowledge/concepts/computerScience.ts
import { ConceptEntity } from "../../types/knowledge";

export const COMPUTER_SCIENCE_CONCEPTS: ConceptEntity[] = [
  {
    id: "sorting-algorithms",
    slug: "/computer-science/dsa/sorting",
    title: "Sorting Algorithm Visualizer Suite",
    subject: "computerScience",
    domain: "Data Structures & Algorithms",
    topic: "Sorting Algorithms",
    description: "Compare time complexities O(N log N) vs O(N^2), stability, in-place swaps, and memory overhead across Bubble, Selection, Insertion, Merge, Quick, and Heap sort.",
    quickAnswer: "Sorting algorithms reorder elements in a specified order; efficient comparison sorts achieve O(N log N) average time complexity.",
    prerequisites: ["html-css-js"],
    nextTopics: ["js-event-loop"],
    siblingTopics: ["logic-gates"],
    relatedLabs: [
      "computer-science/dsa/sorting/bubble-sort",
      "computer-science/dsa/sorting/merge-sort",
      "computer-science/dsa/sorting/quick-sort",
    ],
    relatedBlogs: [],
    difficulty: "intermediate",
    educationalLevel: "undergraduate",
    tags: ["sorting", "big o", "algorithms", "quick sort", "merge sort"],
  },
  {
    id: "osi-model",
    slug: "/computer-science/networking/osi-model",
    title: "7-Layer OSI Model Interactive Lab",
    subject: "computerScience",
    domain: "Computer Networking",
    topic: "Network Models",
    description: "Understand encapsulation and decapsulation from Physical (Layer 1) to Application (Layer 7).",
    quickAnswer: "The OSI model standardizes network communication into 7 distinct layers: Physical, Data Link, Network, Transport, Session, Presentation, and Application.",
    prerequisites: [],
    nextTopics: ["blockchain"],
    siblingTopics: ["logic-gates"],
    relatedLabs: ["computer-science/networking/osi-model"],
    relatedBlogs: [],
    difficulty: "intermediate",
    educationalLevel: "undergraduate",
    tags: ["osi model", "networking", "tcp ip", "encapsulation"],
  },
  {
    id: "logic-gates",
    slug: "/computer-science/logic-gates",
    title: "Digital Logic Gate Simulators",
    subject: "computerScience",
    domain: "Digital Systems",
    topic: "Combinational Logic",
    description: "Interactive truth tables and boolean operations for AND, OR, NOT, NAND, NOR, XOR, and XNOR gates.",
    quickAnswer: "Logic gates are fundamental electronic building blocks that perform boolean functions on binary inputs (0 and 1).",
    prerequisites: [],
    nextTopics: ["sorting-algorithms"],
    siblingTopics: ["osi-model"],
    relatedLabs: [
      "computer-science/logic-gates/and-gate",
      "computer-science/logic-gates/or-gate",
      "computer-science/logic-gates/not-gate",
      "computer-science/logic-gates/nand-gate",
    ],
    relatedBlogs: [],
    difficulty: "beginner",
    educationalLevel: "highSchool",
    tags: ["logic gates", "boolean", "truth table", "and gate"],
  },
  {
    id: "js-event-loop",
    slug: "/computer-science/code-lab/js",
    title: "JavaScript Event Loop & Concurrency Visualizer",
    subject: "computerScience",
    domain: "Programming Languages",
    topic: "JS Concurrency",
    description: "Visualize Call Stack execution, Web APIs, Microtask queue (Promises), Macrotask queue (setTimeout), and rAF.",
    quickAnswer: "The JavaScript event loop manages asynchronous execution by processing microtasks and macrotasks when the Call Stack empties.",
    prerequisites: ["html-css-js"],
    nextTopics: ["sorting-algorithms"],
    siblingTopics: ["html-css-js"],
    relatedLabs: ["computer-science/code-lab/js"],
    relatedBlogs: [],
    difficulty: "intermediate",
    educationalLevel: "undergraduate",
    tags: ["javascript", "event loop", "async", "promises", "callstack"],
  },
  {
    id: "blockchain",
    slug: "/computer-science/blockchain",
    title: "Blockchain Ledger & Cryptographic Hashing",
    subject: "computerScience",
    domain: "Distributed Systems",
    topic: "Blockchain",
    description: "Explore cryptographic SHA-256 hashes, nonce mining, immutability, and distributed ledger consensus.",
    quickAnswer: "A blockchain is a decentralized, cryptographically secured chain of blocks containing immutably recorded transactions.",
    prerequisites: ["osi-model"],
    nextTopics: [],
    siblingTopics: ["osi-model"],
    relatedLabs: ["computer-science/blockchain"],
    relatedBlogs: [],
    difficulty: "intermediate",
    educationalLevel: "undergraduate",
    tags: ["blockchain", "sha256", "nonce", "crypto", "distributed"],
  },
  {
    id: "html-css-js",
    slug: "/computer-science/code-lab/html-css-js",
    title: "Web Development Live Editor Sandbox",
    subject: "computerScience",
    domain: "Web Engineering",
    topic: "Frontend Development",
    description: "Write and execute HTML structure, CSS styling, and JS interactivity live with real-time DOM rendering.",
    quickAnswer: "Web development combines HTML for structure, CSS for presentation, and JavaScript for client-side behavior.",
    prerequisites: [],
    nextTopics: ["js-event-loop"],
    siblingTopics: ["js-event-loop"],
    relatedLabs: ["computer-science/code-lab/html-css-js"],
    relatedBlogs: [],
    difficulty: "beginner",
    educationalLevel: "highSchool",
    tags: ["html", "css", "javascript", "editor", "web dev"],
  },
];
