// app/lib/knowledge/concepts/physics.ts
import { ConceptEntity } from "../../types/knowledge";

export const PHYSICS_CONCEPTS: ConceptEntity[] = [
  {
    id: "uniformmotionlab",
    slug: "/physics/uniformmotionlab",
    title: "Uniform Motion & Constant Velocity",
    subject: "physics",
    domain: "Kinematics",
    topic: "Linear Kinematics",
    description: "Understand constant speed, displacement-time graphs, and zero-acceleration linear motion.",
    quickAnswer: "Uniform motion occurs when an object travels equal distances in equal intervals of time with constant velocity and zero acceleration.",
    prerequisites: [],
    nextTopics: ["freefall", "projectilemotion"],
    siblingTopics: ["freefall"],
    relatedLabs: ["physics/uniformmotionlab"],
    relatedBlogs: [],
    difficulty: "beginner",
    educationalLevel: "middleSchool",
    tags: ["velocity", "speed", "displacement", "kinematics"],
  },
  {
    id: "freefall",
    slug: "/physics/freefall",
    title: "Free Fall Motion under Gravity",
    subject: "physics",
    domain: "Kinematics",
    topic: "Motion under Gravity",
    description: "Learn how objects accelerate uniformly under Earth's gravitational pull without air resistance.",
    quickAnswer: "Free fall is motion under the sole influence of gravity, where all objects accelerate downward at approximately 9.81 m/s² regardless of mass.",
    prerequisites: ["uniformmotionlab"],
    nextTopics: ["projectilemotion", "energyconservation"],
    siblingTopics: ["projectilemotion"],
    relatedLabs: ["physics/freefall"],
    relatedBlogs: [],
    formulas: ["freefall-velocity", "freefall-height"],
    difficulty: "beginner",
    educationalLevel: "highSchool",
    tags: ["gravity", "acceleration", "kinematics", "free fall"],
  },
  {
    id: "projectilemotion",
    slug: "/physics/projectilemotion",
    title: "2D Projectile Motion",
    subject: "physics",
    domain: "Kinematics",
    topic: "2D Kinematics",
    description: "Analyze parabolic trajectories, range, maximum height, and flight time of projected bodies.",
    quickAnswer: "Projectile motion combines constant horizontal velocity with uniform vertical gravitational acceleration to form a parabolic trajectory.",
    prerequisites: ["freefall", "uniformmotionlab"],
    nextTopics: ["energyconservation"],
    siblingTopics: ["freefall"],
    relatedLabs: ["physics/projectilemotion"],
    relatedBlogs: [],
    formulas: ["projectile-range", "projectile-max-height", "projectile-flight-time"],
    difficulty: "intermediate",
    educationalLevel: "highSchool",
    tags: ["trajectory", "parabola", "vectors", "projectile"],
  },
  {
    id: "energyconservation",
    slug: "/physics/energyconservation",
    title: "Mechanical Energy Conservation",
    subject: "physics",
    domain: "Mechanics",
    topic: "Work & Energy",
    description: "Explore kinetic energy, potential energy, and mechanical energy transformation in isolated systems.",
    quickAnswer: "The principle of conservation of mechanical energy states that the total mechanical energy (E = KE + PE) remains constant in an isolated system with conservative forces.",
    prerequisites: ["freefall", "projectilemotion", "hookelaw"],
    nextTopics: ["simplependulum"],
    siblingTopics: ["hookelaw"],
    relatedLabs: ["physics/energyconservation"],
    relatedBlogs: [],
    difficulty: "intermediate",
    educationalLevel: "highSchool",
    tags: ["kinetic energy", "potential energy", "conservation", "work"],
  },
  {
    id: "simplependulum",
    slug: "/physics/simplependulum",
    title: "Simple Pendulum Oscillation",
    subject: "physics",
    domain: "Oscillations & Waves",
    topic: "Simple Harmonic Motion",
    description: "Explore periodic oscillation, small-angle approximation, period, and restoring forces.",
    quickAnswer: "A simple pendulum oscillates in Simple Harmonic Motion with a period proportional to the square root of string length divided by acceleration due to gravity.",
    prerequisites: ["freefall"],
    nextTopics: ["waveoptics"],
    siblingTopics: ["hookelaw"],
    relatedLabs: ["physics/simplependulum"],
    relatedBlogs: [],
    formulas: ["pendulum-period"],
    difficulty: "beginner",
    educationalLevel: "highSchool",
    tags: ["shm", "pendulum", "period", "oscillation"],
  },
  {
    id: "hookelaw",
    slug: "/physics/hookelaw",
    title: "Hooke's Law & Elasticity",
    subject: "physics",
    domain: "Mechanics",
    topic: "Elastic Forces",
    description: "Investigate spring stiffness (k), restoring force, and elastic potential energy.",
    quickAnswer: "Hooke's Law states that restoring force in a spring is directly proportional to displacement: F = -k * x.",
    prerequisites: ["freefall"],
    nextTopics: ["energyconservation"],
    siblingTopics: ["simplependulum"],
    relatedLabs: ["physics/hookelaw"],
    relatedBlogs: [],
    formulas: ["hooke-force"],
    difficulty: "beginner",
    educationalLevel: "highSchool",
    tags: ["spring", "elasticity", "force", "hooke"],
  },
  {
    id: "ohmslaw",
    slug: "/physics/ohmslaw",
    title: "Ohm's Law & DC Circuits",
    subject: "physics",
    domain: "Electricity & Magnetism",
    topic: "Circuit Analysis",
    description: "Master voltage, current, resistance, and electrical power relations in DC circuits.",
    quickAnswer: "Ohm's Law establishes that electric current (I) flowing through a conductor is proportional to voltage (V) and inversely proportional to resistance (R): V = I * R.",
    prerequisites: [],
    nextTopics: ["rclab"],
    siblingTopics: ["rclab"],
    relatedLabs: ["physics/ohmslaw"],
    relatedBlogs: [],
    formulas: ["ohm-law-v", "power-law"],
    difficulty: "beginner",
    educationalLevel: "highSchool",
    tags: ["voltage", "current", "resistance", "circuits"],
  },
  {
    id: "rclab",
    slug: "/physics/rclab",
    title: "RC Circuit Transient Response",
    subject: "physics",
    domain: "Electricity & Magnetism",
    topic: "Transient Circuits",
    description: "Observe exponential capacitor charging, discharging curves, and the tau (RC) time constant.",
    quickAnswer: "An RC circuit contains a resistor and capacitor; its charging and discharging voltage follows exponential decay governed by time constant tau = R * C.",
    prerequisites: ["ohmslaw"],
    nextTopics: [],
    siblingTopics: ["ohmslaw"],
    relatedLabs: ["physics/rclab"],
    relatedBlogs: [],
    formulas: ["rc-time-constant"],
    difficulty: "intermediate",
    educationalLevel: "undergraduate",
    tags: ["capacitor", "transient", "time constant", "rc circuit"],
  },
  {
    id: "waveoptics",
    slug: "/physics/waveoptics",
    title: "Wave Optics & Interference",
    subject: "physics",
    domain: "Optics",
    topic: "Physical Optics",
    description: "Explore wave nature of light, double-slit interference, diffraction patterns, and fringe width.",
    quickAnswer: "Wave optics models light as electromagnetic waves undergoing constructive and destructive interference.",
    prerequisites: ["simplependulum"],
    nextTopics: ["speedoflight"],
    siblingTopics: ["opticslens"],
    relatedLabs: ["physics/waveoptics"],
    relatedBlogs: [],
    difficulty: "intermediate",
    educationalLevel: "undergraduate",
    tags: ["interference", "diffraction", "wave optics", "youngs double slit"],
  },
  {
    id: "opticslens",
    slug: "/physics/opticslens",
    title: "Geometric Optics & Lens Formula",
    subject: "physics",
    domain: "Optics",
    topic: "Geometric Optics",
    description: "Study focal length, convex and concave lenses, thin lens equation, and magnification.",
    quickAnswer: "Geometric optics treats light rays propagating in straight lines, focusing through lenses according to 1/f = 1/v - 1/u.",
    prerequisites: [],
    nextTopics: ["waveoptics"],
    siblingTopics: ["waveoptics"],
    relatedLabs: ["physics/opticslens"],
    relatedBlogs: [],
    difficulty: "beginner",
    educationalLevel: "highSchool",
    tags: ["lenses", "optics", "focal length", "refraction"],
  },
  {
    id: "speedoflight",
    slug: "/physics/speedoflight",
    title: "Speed of Light & Electromagnetic Propagation",
    subject: "physics",
    domain: "Optics",
    topic: "Electromagnetism",
    description: "Measure the speed of light c = 299,792,458 m/s, refractive index, and wave speed equation c = f * lambda.",
    quickAnswer: "The speed of light in vacuum (c) is a fundamental physical constant equal to exactly 299,792,458 m/s.",
    prerequisites: ["waveoptics"],
    nextTopics: [],
    siblingTopics: ["waveoptics"],
    relatedLabs: ["physics/speedoflight"],
    relatedBlogs: [],
    difficulty: "intermediate",
    educationalLevel: "undergraduate",
    tags: ["speed of light", "electromagnetic", "frequency", "wavelength"],
  },
];
