// app/physics/faradays-law/page.tsx
import type { Metadata } from "next";
import PhysicsExperimentLanding from "@/components/PhysicsExperimentLanding";
import { createLabMetadata } from "@/app/lib/seo/metadata";

const PAGE_TITLE = "Electromagnetic Induction & Faraday's Law Simulator";
const PAGE_DESCRIPTION = "Explore Faraday's Law (ε = -N dΦ/dt), magnetic flux linkage, Lenz's law, AC dynamo generator induction, and live sinusoidal oscilloscope waveforms online.";

export const metadata: Metadata = createLabMetadata({
  title: PAGE_TITLE,
  description: PAGE_DESCRIPTION,
  pathname: "/physics/faradays-law",
  subject: "physics",
  topic: "Electromagnetic Induction & Faraday's Law",
  keywords: [
    "faradays law simulation",
    "electromagnetic induction virtual lab",
    "lenzs law simulator",
    "magnetic flux linkage calculator",
    "ac generator simulation",
    "induced electromotive force EMF",
    "physics virtual lab"
  ],
});

const FAQS = [
  {
    question: "What does Faraday's Law of Induction state?",
    answer: "Faraday's Law states that the induced electromotive force (EMF, ε) in any closed circuit is equal to the negative time rate of change of magnetic flux (dΦ_B/dt) through the circuit multiplied by the number of coil turns (N): ε = -N (dΦ_B/dt).",
  },
  {
    question: "What is Lenz's Law and why is there a negative sign?",
    answer: "Lenz's Law states that the induced electric current always creates a secondary magnetic field that opposes the original change in magnetic flux that produced it, enforcing the law of conservation of energy.",
  },
  {
    question: "Why does moving the magnet faster produce a brighter lightbulb glow?",
    answer: "Faster magnet motion increases the rate of change of magnetic flux (dΦ_B/dt), which directly raises the induced voltage (EMF). Because electrical power delivered to the filament scales with the square of voltage (P = V²/R), the bulb glows significantly brighter.",
  },
  {
    question: "How does an AC Dynamo generator work?",
    answer: "Rotating a magnetic dipole inside a coil at angular speed ω causes the magnetic flux to vary sinusoidally (Φ = B·A·cos(ωt)), producing a continuous alternating sinusoidal EMF (ε = N·ω·B·A·sin(ωt)).",
  },
];

export default function FaradaysLawPage() {
  return (
    <PhysicsExperimentLanding
      slug="faradays-law"
      title="Electromagnetic Induction"
      description="Explore Faraday's Law, magnetic flux, Lenz's law, and AC dynamo electrical generators in real time."
      heroDescription="Experience the foundation of modern electrical power generation. Drag permanent bar magnets through copper coils or spin an AC dynamo to induce EMF, illuminate load bulbs, and observe live sinusoidal oscilloscope traces."
      theory="Faraday's Law describes how a time-varying magnetic field induces an electromotive force (EMF) in a conducting loop. The magnitude of the induced voltage depends directly on the rate of flux change and the number of turns."
      formula="\\mathcal{E} = -N \\frac{d\\Phi_B}{dt}"
      formulaLabel="Faraday's induction law"
      launchUrl="/labs/physics/faradays-law"
      heroImageUrl="/images/physics/faradays-law-hero.png"
      visualLabel="Magnetic induction model"
      visualDetail="Magnet velocity, flux density, AC generator"
      accent={{ primary: "#0ea5e9", secondary: "#3b82f6", warm: "#f59e0b" }}
      learningObjectives={[
        "Calculate magnetic flux (ΦB = B · A · cos θ) and induced EMF.",
        "Apply Lenz's Law and right-hand rules to determine induced current direction.",
        "Investigate the relationship between magnet velocity, coil turn count, and induced voltage.",
        "Trace continuous alternating voltage waveforms generated by AC dynamos.",
      ]}
      applications={[
        "Hydroelectric and wind turbine electrical power generation",
        "Power grid step-up and step-down transformers",
        "Flameless electromagnetic induction cooktops",
        "Wireless inductive resonant smartphone charging pads",
      ]}
      faqs={FAQS}
    />
  );
}
